name: GDQ Website Scraper

on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  python_scraper:
    runs-on: ubuntu-latest
    steps:
    - name: Get current time
      uses: gerred/actions/current-time@master
      id: current-time
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Continue pulling SGDQ 2020 from live counters
      run: python3 scripts/main.py
    - name: Pull archive data
      run: python3 scripts/get_archive_data.py
    - run: git add .
    - run: git status
    - run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "${{ steps.current-time.outputs.time }} | Data update"
    - run: git push
